### ISSUE TITLE
Faction "Controlling" does not work.

### ISSUE THREAD

**Issue by PumknNutz** [PumknNutz/EICSystemTracker#1]
When choosing "Controlling" from one of the factions. It doesn't appear to work.

**Comment by KonigKhan** [comment]
Pending fix for this.

**Comment by PumknNutz** [comment]
fix will be included in Beta 1.8

**Comment by VoggixHavenwhite** [comment]
Reopened - tested in 1.8 and does not tag in the DB

**Comment by PumknNutz** [comment]
fixed in 1.10
