### ISSUE TITLE
CZ and Bounty Hunting data mapping issue

### ISSUE THREAD

**Issue by VoggixHavenwhite** [PumknNutz/EICSystemTracker#11]
Currently Combat Zone and Bounty Hunting both point to the same data element "Credits Claimed".  These need to be unique

**Comment by PumknNutz** [comment]
The intent was for them to both use "credits claimed" and you can filter the table on type. This can be separate if you would like.

**Comment by VoggixHavenwhite** [comment]
I see where you're going here.  We can set this aside for now.
