### ISSUE TITLE
Add text box for screenshots

### ISSUE THREAD

**Issue by VoggixHavenwhite** [PumknNutz/EICSystemTracker#12]
Pease add a text box on activity tracking tab "For any activities tied to a contest please retain screenshots of your in-game transaction for validation"

**Comment by VoggixHavenwhite** [comment]
This is an easy one right?  I may have promised some people this would be in the next release...

**Comment by PumknNutz** [comment]
@VoggixHavenwhite Yes this will be in next release.

**Comment by PumknNutz** [comment]
Included in Beta 1.7
