### ISSUE TITLE
Retired factions still showing in pie chart

### ISSUE THREAD

**Issue by VoggixHavenwhite** [PumknNutz/EICSystemTracker#2]
Example - I tracked Dakvar this morning the pre-fill worked great, I removed Bandizel Gold Gang and added EIC and submitted.  Upon viewing the system Bandizel was still showing in the list and in the chart.

**Comment by PumknNutz** [comment]
Fixed by setting influence to 0 when user clicks the "x" on the factions page. (This is how the UI is filtering out existing factions).
