### ISSUE TITLE
Faction Tracking is loading too many factions

### ISSUE THREAD

**Issue by VoggixHavenwhite** [PumknNutz/EICSystemTracker#21]
Pre-load is pulling in all factions ever associated instead of most recent timestamp

**Comment by VoggixHavenwhite** [comment]
sproc programmed to rectify
dbo.NewFactionFetchUI
input system name - returns all pertinent details

**Comment by PumknNutz** [comment]
Will be added for next release.

**Comment by PumknNutz** [comment]
fixed in 1.10
