### ISSUE TITLE
Activity Log not starting

### ISSUE THREAD

**Issue by VoggixHavenwhite** [PumknNutz/EICSystemTracker#4]
Clicked on Activity Log - nothing appeared on the screen.  Realized verbose logging probably was not turned on.  Edited AppConfig.xml to correct.  Restarted game, still nothing appeared when clicking on Activity Log.

**Comment by PumknNutz** [comment]
Activity log is where users can track their activities in system. This is added in the next beta (1.4)

**Comment by VoggixHavenwhite** [comment]
Log page is now functioning
